### PR TITLE
Adds avro file support

### PR DESCRIPTION
**Pull request by ollietulloch**
- Adds avro file helper where `rows` returns a table of data  (array of arrays); the first being the "header", all others are the data
- Adds `NdrImport::Avro::Table` that ensures `header_lines` and `footer_lines` are always 1 and 0 respectively. All other "table" logic is inherited from `NdrImport::Table`
- #93

### CODE REVIEW

**Comment by timgentry** [comment]
Looks good. @ollietulloch is it worth putting in a class method like `NdrImport::Avro::Table.from_schema(safe_path)` that returns a new instance of `NdrImport::Avro::Table` seeded from the Acro schema? It could then be serialised in YAML as a scaffold transformation, or used to feed a like-for-like import process automatically?

**Comment by timgentry** [comment]
Also @bshand, at what point do you think these should be farmed out to new gems, so that every install doesn't need every filetype dependency?

**Comment by ollietulloch** [comment]
> Looks good. @ollietulloch is it worth putting in a class method like `NdrImport::Avro::Table.from_schema(safe_path)` that returns a new instance of `NdrImport::Avro::Table` seeded from the Acro schema? It could then be serialised in YAML as a scaffold transformation, or used to feed a like-for-like import process automatically?

@timgentry - nice idea, I'll take a look

**Comment by ollietulloch** [comment]
> > Looks good. @ollietulloch is it worth putting in a class method like `NdrImport::Avro::Table.from_schema(safe_path)` that returns a new instance of `NdrImport::Avro::Table` seeded from the Acro schema? It could then be serialised in YAML as a scaffold transformation, or used to feed a like-for-like import process automatically?
> 
> @timgentry - nice idea, I'll take a look

@timgentry - initial commit here: 07914c2. It just scaffolds basic column mappings for now

**Comment by timgentry** [comment]
@ollietulloch Looks good to me. @bshand can you merge if you're happy with it?

**Comment by timgentry** [comment]
This will resolve #94

**Review by bshand — APPROVED** [review]
Yes, this all looks good: I'll merge it now.

**Pull request merged**
